package rewriter

import (
	"bytes"
	"fmt"
	"strings"
)

// The reflection prompt reproduces AgentDiet's four parts (arXiv 2509.23586
// §2.3.1): job description, I/O format with steps wrapped in <step id="…">,
// examples of the three waste categories, and guidelines against information
// loss. The paper defers its verbatim prompt to the figshare artifact, so this
// is a reconstruction from the published outline, not a copy.
// PromptVersion identifies this prompt. A content-addressed rewrite store MUST
// key on SHA-256(stepBytes) || PromptVersion, never on the step hash alone:
// otherwise an edited prompt keeps replaying rewrites generated by the previous
// one, and the store silently mixes two mechanisms whose outputs the replay
// grid priced separately. Bump it on ANY edit to systemPrompt or to the
// user-message rendering.
const PromptVersion = "1"

const (
	promptPartJob        = "## Your job"
	promptPartIOFormat   = "## Input and output format"
	promptPartWaste      = "## The three kinds of waste"
	promptPartGuidelines = "## Guidelines: condense, never delete"
)

const systemPrompt = promptPartJob + `

You analyse one step of an agent trajectory that is solving a software task, and
you rewrite that single step so it carries the same decision-relevant
information in fewer tokens. You are not solving the task and you are not
advising the agent. The agent is unaware of you and will read your rewrite as if
it were the original tool output.

` + promptPartIOFormat + `

The input is a window of consecutive trajectory steps. Each step is wrapped in
<step id="…">…</step>. Exactly one step is named as the target. Steps before and
after the target are context only: they tell you what the agent already knows
and what it did next, so you can judge what is still load-bearing.

Output the rewritten body of the target step and nothing else. No preamble, no
explanation, no markdown fences, no <step> wrapper. Keep the internal structure
of the original body (its own tags, table shape, ordering) intact.

` + promptPartWaste + `

1. USELESS — content that never mattered to anyone. Build chatter, progress
   bars, __pycache__ and .git entries in a listing, dependency-resolution
   noise, repeated banner lines.
2. REDUNDANT — content already present elsewhere in the window. An editor tool
   echoing back the exact text that was just written, a file body the agent
   retrieved two steps ago, the same warning emitted per file.
3. EXPIRED — content that mattered when it was produced but no longer can. The
   full listing from a grep whose candidates the agent has since narrowed to one
   file; environment probing the agent has already concluded.

` + promptPartGuidelines + `

- Replace what you remove with a short takeaway that says what was there, e.g.
  "individual test lines omitted; 214 PASSED" or "37 __pycache__ entries
  omitted". Never delete a region and leave nothing in its place.
- Keep every failure verbatim: FAIL / FAILED / ERROR / exception / traceback /
  panic / fatal lines, non-zero exit codes and statuses, and the file paths,
  line numbers and column numbers named on those lines. Copy them character for
  character. An elided failure costs the agent a wasted turn or a wrong fix.
- Keep identifiers exactly as written — test names, symbols, hashes, versions,
  flags, URLs. Do not normalise, abbreviate or reformat them.
- Keep anything the agent has not acted on yet: a diff it has not applied,
  output it has not read, a question it has not answered.
- When a step contains nothing you can safely condense, return it unchanged.
  That is a correct answer; a lossy rewrite is not.`

// buildUserMessage renders the reflection window as <step id="…"> XML and names
// the target. Ids count backwards from the newest step, matching the paper's
// s / s-1 / s-2 notation, so the target of a well-formed a=2 window is "s-2".
//
// If StepBytes is not one of WindowBytes the window is dropped and the target
// is presented alone: a caller-side mismatch must never end with the module
// rewriting a step other than the one it was handed.
func buildUserMessage(req Request) string {
	window := req.WindowBytes
	target := -1
	for i := range window {
		if bytes.Equal(window[i], req.StepBytes) {
			target = i
			break
		}
	}
	if target < 0 {
		window = [][]byte{req.StepBytes}
		target = 0
	}

	var b strings.Builder
	for i, step := range window {
		id := stepID(i, len(window))
		// Step bodies are embedded raw. Escaping them would put entity-encoded
		// text on the wire if the model echoed it back, and corrupting the block
		// is worse than a confused delimiter — which the acceptance gate catches.
		fmt.Fprintf(&b, "<step id=%q>\n%s\n</step>\n", id, step)
	}

	tool := strings.TrimSpace(req.ToolName)
	if tool == "" {
		tool = "unknown"
	}
	fmt.Fprintf(&b, "\nTarget step: %q (produced by the %s tool).\n", stepID(target, len(window)), tool)
	b.WriteString("Rewrite the body of that step only.")
	return b.String()
}

func stepID(index, total int) string {
	back := total - 1 - index
	if back == 0 {
		return "s"
	}
	return fmt.Sprintf("s-%d", back)
}
